### PR TITLE
Wynand/less to scss

### PR DESCRIPTION
**Pull request by WynieCronje**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

### CODE REVIEW

**Comment by waterplea** [comment]
@WynieCronje from a brief look at the 800+ files in this PR I got the impression that you migrated the whole library to SASS and Angular 11 :) We cannot do that because we need other post-Ivy Angular apps to support Taiga, that's why we settled on Angular 9. As for LESS to SASS, what is the point of it? Internal realization is not a concern for apps. If you want to use mixins from Taiga in SASS apps we can add SASS copy of mixins while keeping LESS too because we need them.

**Comment by WynieCronje** [comment]
Apologies :)  I was under the impression I did a PR from my `forked repo branch` to `forked repo main`.

I was just playing around as a personal challenge to see if I can do it. And what the effort is 😄  .

It actually all started when I tried to create a less function to convert PX to EM. (Less functions are tricky to implement).

I'll Close the PR

**Comment by waterplea** [comment]
@WynieCronje if you want, you can add a SCSS copy of our mixins, actually. They do not change that often so I think we can support both versions for those who use SASS.

**Comment by awtkeithlin** [comment]
[you can add a SCSS copy of our mixins]  => How to do?
I have a project use sass. who to use less taiga?

**Comment by waterplea** [comment]
@awtkeithlin SASS mixins are coming in the next release, but you do not really need them. You can use Taiga with SCSS project, just follow the Getting started guidelines. Starter is a good idea, I think we can add it, what do you think, @MarsiBarsi?

**Comment by awtkeithlin** [comment]
I ng new test project and follow by doc but it doesn't work. @waterplea 
https://github.com/awtkeithlin/testTaiga

**Comment by WynieCronje** [comment]
If you import  the TuiButtonModule, it should work :)

**Comment by awtkeithlin** [comment]
ok it worked. thx!

**Pull request closed without merging**
