### PR TITLE
feat(core): add scss mixin support

### LINKED ISSUE #164: [FEATURE] Add mixin support for SASS
# 🚀 Feature request

### Describe the solution you'd like
be able to use the mixins with SASS

### PR DESCRIPTION
**Pull request by WynieCronje**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [X] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [X] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [X] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

SASS users cant use
```css
@import '~@taiga-ui/core/styles/taiga-ui-local';
```

Closes #164 

## What is the new behavior?
SASS users can safely use below
```css
@import '~@taiga-ui/core/styles/taiga-ui-local';
```

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [X] No

### CODE REVIEW

**Comment by WynieCronje** [comment]
I added new files next to less files as a reminder to change scss files when working on less files:

image

**Comment by WynieCronje** [comment]
@waterplea  do not accept yet. Found an issue

**Comment by WynieCronje** [comment]
I realized my SASS was outdated from previous branch.

**Comment by WynieCronje** [comment]
> @waterplea  do not accept yet. Found an issue

Been fixed

**Review by waterplea — APPROVED** [review]

**Review by MarsiBarsi — APPROVED** [review]
Thank you very much!

**Comment by JohanHeyvaert** [comment]
I don't think this change allows us to use the **grid** mixins from a scss file, or does it?
The grid mixins are in markup/tui-row.less. I don't see a scss version of the files in the markup directory.

Side question 1: why there is not a scss version of taiga-ui-global.less (which import tui-row.less)? Probably because the files in markup don't have a scss version yet either?
Side question 2: when would one use taiga-ui-global.less instead of taiga-ui-local.less?

Thanks for your response!

**Comment by waterplea** [comment]
Hi @JohanHeyvaert 
Grid is in global styles. These are global classes and not mixins. There is no SCSS global file because it doesn't matter what it uses, you just add it to angular.json and Angular does everything you need. You add global there once. You add local whenever you need to use a mixin in a file.

I would recommend to use your own layout classes or some dedicated library like Tailwind. Global classes are somewhat limited in Taiga UI and I believe we should drop most of them someday in a major release. We cannot compete with dedicated solutions 🙂

**Pull request merged**
