### PR TITLE
ci: use issue forms for issue creation

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [x] Other... Please describe: docs

## What is the current behavior?

Users can only create a bug or feature, they do not have the ability to specify what type of bug or feature they would like

## What is the new behavior?

It will be convenient for users to fill out forms on the site

image

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by splincode** [comment]
@waterplea what do you think?)

**Comment by splincode** [comment]
@waterplea @IKatsuba @MarsiBarsi @vladimirpotekhin @nsbarsukov friendly ping :)
what do you think about improve UX for create issues? any ideas ))

-----

[Reference]

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

**Comment by waterplea** [comment]
Let's merge and tweak it if needed.

**Review by waterplea — APPROVED** [review]

**Comment by vladimirpotekhin** [comment]
Shouldn't we make other issue templates the same way?

**Review by vladimirpotekhin — APPROVED** [review]

**Comment by splincode** [comment]
`Shouldn't we make other issue templates the same way?`

Yes)) this is the first experiment

**Pull request merged**
