### PR TITLE
fix(kit): kit dependencies fixed

### LINKED ISSUE #979: 🐞 - @ng-web-apis/mutation-observer is missing after update to 2.22.0
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

_No response_

### Description

After running `npm update` from Taiga 2.21.0 to 2.22.0 and running build, I get the following error:

```
Error: The target entry-point "@taiga-ui/kit" has missing dependencies:
 - @ng-web-apis/mutation-observer
```

In `package-lock.json` I have:
```
"node_modules/@taiga-ui/cdk/node_modules/@ng-web-apis/mutation-observer": {
      "version": "1.1.0",
      "resolved": "https://registry.npmjs.org/@ng-web-apis/mutation-observer/-/mutation-observer-1.1.0.tgz",
      "integrity": "sha512-ThcsCaGCXf07xvIAFdP967MVxE74rH6dfZtoKky6RR69aMhdPz0AQuevVKIpcX4mU2P3ROpZhqP8MGhWD7DnOg==",
      "dependencies": {
        "tslib": "^1.9.0"
      },
      "peerDependencies": {
        "@angular/core": ">=6.0.0",
        "@ng-web-apis/common": ">=1.1.0"
      }
    },
```

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by tim99919**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring
-   [ ] Code style update
-   [ ] Build or CI related changes
-   [ ] Documentation content changes

## What is the current behavior?

Closes #979  

## What is the new behavior?

External libs moved to dependencies in kit-lib package.json file. @ng-web-apis/mutation-observer lib added to dependencies. It was a bug with mutation-observer lib when it not uses globally in angular app.

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by waterplea** [comment]
This is unnecessary. Kit cannot exist without cdk and cdk already packs those deps.

**Comment by tim99919** [comment]
You're right. But still strange behavior when installing taigaui lib

image

**Comment by waterplea** [comment]
If you have issues after installing, please remove `node_modules`, `package-lock.json` and maybe do `cache clean` and then do a clean `npm i`

**Comment by tim99919** [comment]
I have done this several times. Nothing helps. Also I created a new project and tried to add the taiga-ui lib, but creating the application causes the same problem with mutation-observer in taiga-ui/kit

**Comment by splincode** [comment]
@tim99919 please, create a minimal reproduce repo on Github

**Comment by tim99919** [comment]
@splincode https://github.com/tim99919/angular-taiga-ui-lib-test

**Comment by splincode** [comment]
After `$ npm ci`

image

image

image

@waterplea is it correct behaviour?

**Comment by waterplea** [comment]
4 @ng-web-apis packages should get installed and be available for app code and Taiga UI packages:
```
common
intersection-observer
mutation-observer
resize-observer
```
@splincode would you look into that? Clean project with `package.json` from this issue seems to reproduce the issue:
https://github.com/TinkoffCreditSystems/taiga-ui/issues/979

**Pull request closed without merging**
