### PR TITLE
feat(kit): `decimalSeparator` for input value decimals formatting

### PR DESCRIPTION
**Pull request by shoom3301**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [x] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by waterplea** [comment]
I feel this should rather be a i18n token of numbers internationalization of some kind. We probably need to carefully read this stuff :)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

**Comment by waterplea** [comment]
@vladimirpotekhin @nsbarsukov @MarsiBarsi what do you think? Maybe add a token `TUI_NUMBER_FORMAT` with an object of one key `decimalSeparator` for the time being? I don't think people need to change it on the fly, right @shoom3301? It would also be used in `tui-money` component as well.

**Comment by MarsiBarsi** [comment]
> @vladimirpotekhin @nsbarsukov @MarsiBarsi what do you think? Maybe add a token `TUI_NUMBER_FORMAT` with an object of one key `decimalSeparator` for the time being? I don't think people need to change it on the fly, right @shoom3301? It would also be used in `tui-money` component as well.

Sure, I like the idea of one DI token because we can set these rules for the whole app once

**Comment by waterplea** [comment]
Looks like `core` package is a good place for it to go. @shoom3301 will you add it please? Here are all the places where it should be used:

- `Money` component
- `InputNumber` component
- `InputSlider` component
- `InputRange` component
- `FormatNumber` pipe, default value for the decimal separator

**Comment by shoom3301** [comment]
https://github.com/TinkoffCreditSystems/taiga-ui/pull/676

**Pull request closed without merging**
