### PR TITLE
Feature/highlight custom color

### LINKED ISSUE #925: 🚀 - Add color attribute for Highlight
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

New attribute `tuiHighlightColor` to control the color of the Highlight.
Discussed #919

### PR DESCRIPTION
**Pull request by afifalfiano**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [x] Feature
-   [ ] Refactoring
-   [ ] Code style update
-   [ ] Build or CI related changes
-   [ ] Documentation content changes

## What is the current behavior?
Can't customize color on highlight directive

Closes #925 https://github.com/TinkoffCreditSystems/taiga-ui/issues/925

## What is the new behavior?
Can customize color on highlight directive. Add new attribute [tuiHighlightColor] to customize highlight color

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Review by waterplea — CHANGES_REQUESTED** [review]
Hey, thanks for picking this up. Let's add a second input instead 🙂 it should be easier to use this way

**Comment by afifalfiano** [comment]
> Hey, thanks for picking this up. Let's add a second input instead 🙂 it should be easier to use this way

Oh oke, Let me fix now 😅

**Comment by afifalfiano** [comment]
Hi, @waterplea I have fixed it, please review for the changes. ️😃

**Comment by splincode** [comment]
duplicated https://github.com/TinkoffCreditSystems/taiga-ui/pull/1065/files

**Comment by afifalfiano** [comment]
> duplicated https://github.com/TinkoffCreditSystems/taiga-ui/pull/1065/files

I think I'm the first to handle this issue. How?

**Review by waterplea — APPROVED** [review]

**Comment by waterplea** [comment]
> > duplicated https://github.com/TinkoffCreditSystems/taiga-ui/pull/1065/files
> 
> I think I'm the first to handle this issue. How?

Yes, your PR was the first so I'll merge it and we can merge in tests from the second one since they are compatible :D

**Review by MarsiBarsi — APPROVED** [review]

**Pull request merged**
